/*
 * Neasdf_DNSContext
 *
 * EASDF DNS Context Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.556 V17.3.0; 5G System; Edge Application Server Discovery Services; Stage3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.556/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// DNS Response message detection template
type DnsRspMdt struct {
	MdtId               string                    `json:"mdtId" yaml:"mdtId" bson:"mdtId,omitempty"`
	Label               string                    `json:"label,omitempty" yaml:"label" bson:"label,omitempty"`
	FqdnPatternList     []FqdnPatternMatchingRule `json:"fqdnPatternList,omitempty" yaml:"fqdnPatternList" bson:"fqdnPatternList,omitempty"`
	EasIpv4AddrRanges   []Ipv4AddressRange        `json:"easIpv4AddrRanges,omitempty" yaml:"easIpv4AddrRanges" bson:"easIpv4AddrRanges,omitempty"`
	EasIpv6PrefixRanges []Ipv6PrefixRange         `json:"easIpv6PrefixRanges,omitempty" yaml:"easIpv6PrefixRanges" bson:"easIpv6PrefixRanges,omitempty"`
}
