/*
 * Neasdf_DNSContext
 *
 * EASDF DNS Context Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.556 V17.3.0; 5G System; Edge Application Server Discovery Services; Stage3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.556/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Action to apply to DNS messages matching a message detection template
type Action struct {
	ApplyAction           ApplyAction           `json:"applyAction" yaml:"applyAction" bson:"applyAction,omitempty"`
	FwdParas              *ForwardingParameters `json:"fwdParas,omitempty" yaml:"fwdParas" bson:"fwdParas,omitempty"`
	ReportingOnceInd      bool                  `json:"reportingOnceInd,omitempty" yaml:"reportingOnceInd" bson:"reportingOnceInd,omitempty"`
	ResetReportingOnceInd bool                  `json:"resetReportingOnceInd,omitempty" yaml:"resetReportingOnceInd" bson:"resetReportingOnceInd,omitempty"`
}
