/*
 * Neasdf_DNSContext
 *
 * EASDF DNS Context Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.556 V17.3.0; 5G System; Edge Application Server Discovery Services; Stage3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.556/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// DNS Response Event Report
type DnsRspReport struct {
	// Fully Qualified Domain Name
	Fqdn             string     `json:"fqdn,omitempty" yaml:"fqdn" bson:"fqdn,omitempty"`
	EasIpv4Addresses []string   `json:"easIpv4Addresses,omitempty" yaml:"easIpv4Addresses" bson:"easIpv4Addresses,omitempty"`
	EasIpv6Addresses []string   `json:"easIpv6Addresses,omitempty" yaml:"easIpv6Addresses" bson:"easIpv6Addresses,omitempty"`
	EcsOption        *EcsOption `json:"ecsOption,omitempty" yaml:"ecsOption" bson:"ecsOption,omitempty"`
}
