/*
 * Neasdf_DNSContext
 *
 * EASDF DNS Context Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.556 V17.3.0; 5G System; Edge Application Server Discovery Services; Stage3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.556/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import "time"

// DNS context event report
type DnsContextEventReport struct {
	// string with format 'date-time' as defined in OpenAPI.
	Timestamp *time.Time `json:"timestamp" yaml:"timestamp" bson:"timestamp,omitempty"`
	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer.
	DnsRuleId      int32           `json:"dnsRuleId,omitempty" yaml:"dnsRuleId" bson:"dnsRuleId,omitempty"`
	DnsQueryReport *DnsQueryReport `json:"dnsQueryReport,omitempty" yaml:"dnsQueryReport" bson:"dnsQueryReport,omitempty"`
	DnsRspReport   *DnsRspReport   `json:"dnsRspReport,omitempty" yaml:"dnsRspReport" bson:"dnsRspReport,omitempty"`
	DnsMsgId       string          `json:"dnsMsgId,omitempty" yaml:"dnsMsgId" bson:"dnsMsgId,omitempty"`
}
