/*
 * Neasdf_BaselineDNSPattern
 *
 * EASDF Baseline DNS Pattern Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.556 V17.3.0; 5G System; Edge Application Server Discovery Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.556/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Baseline DNS message detection template
type BaselineDnsMdt struct {
	MdtId string `json:"mdtId" yaml:"mdtId" bson:"mdtId,omitempty"`
	Label string `json:"label,omitempty" yaml:"label" bson:"label,omitempty"`
	// map of DNS query message detection templates where a valid JSON string serves as key
	DnsQueryMdtList map[string]DnsQueryMdt `json:"dnsQueryMdtList,omitempty" yaml:"dnsQueryMdtList" bson:"dnsQueryMdtList,omitempty"`
	// map of DNS response message detection templates where a valid JSON string serves as key
	DnsRspMdtList map[string]DnsRspMdt `json:"dnsRspMdtList,omitempty" yaml:"dnsRspMdtList" bson:"dnsRspMdtList,omitempty"`
}
